services:
  eval:
    build:
      context: ../..  # Root of project
      dockerfile: eval/docker/Dockerfile
    ports:
      - "6901:6901"
    shm_size: 512m
    volumes:
      # Mount code and test files read-only
      - ../../pixelpilot:/app/pixelpilot:ro
      - ../../tests:/app/tests:ro
      - ../../eval:/app/eval:ro
      # Mount test cases and artifacts with write access for results
      - ../../eval/test_cases:/app/eval/test_cases:ro
      - ../../eval/artifacts:/app/eval/artifacts
    environment:
      - DISPLAY=:1
      - VNC_PW=ai
      - PYTHONUNBUFFERED=1
      - MODE=${MODE:-eval}  # Default to eval mode
      - PYTEST_ADDOPTS="--color=yes"  # Force colored output for tests
      - SSL_CERT_GEN=false  # Disable SSL cert generation
      - KASM_VNC_CERT_CN=localhost  # Set certificate common name
      - KASM_VNC_CERT=/home/ai/.vnc/self.pem  # Certificate path
      - KASM_VNC_KEY=/home/ai/.vnc/self.key   # Key path
    env_file:
      - ../../.env
    command: /app/eval/docker/scripts/container_entrypoint.sh ${MODE:-eval} 