services:
  eval:
    build:
      context: ../..  # Root of project
      dockerfile: eval/docker/Dockerfile.x11
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "5900:5900"
    environment:
      - DISPLAY=:0
    volumes:
      - ../../eval/test_cases:/app/eval/test_cases:ro
      - ../../eval/artifacts:/app/eval/artifacts
      - ../../pixelpilot:/app/pixelpilot:ro
      - ../../eval:/app/eval:ro
    env_file:
      - ../../.env
    # Use our improved script
    command: /run-eval.sh
